[versions]
agp = "8.12.0"
kotlin = "2.2.0"
activity = "1.12.0-alpha05"
compose = "1.9.0-rc01"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
